# spherical colvar file
colvarstrajfrequency         100000
colvarsrestartfrequency      100000

# returns the distance between two groups
colvar {
  name radius
  outputappliedforce         on
  distance {
    group1 {
      atomsFile             colvar.pdb       # the ligand atoms
      atomsCol              O
      atomsColValue         1
    }
    group2 {
      atomsFile              colvar.pdb      #the receptor atoms
      atomsCol               O
      atomsColValue          2
    }
  }
}

# given the values provided by the above colvar(s), will apply a force to center the colvars
harmonic {
  name umbradius
  colvars radius
  forceConstant              90.0            #force constant kcal/mol-angstrom^2
  centers                    7.5      # equilibrium value at which the restraints are centered
}

